# Generated by Django 2.0.7 on 2018-08-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_moviedbinfo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedbinfo',
            name='last_synced',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
