# Generated by Django 2.0.7 on 2018-08-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20180807_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
