# Generated by Django 2.0.7 on 2018-08-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_favorites_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedbinfo',
            name='data',
            field=models.TextField(blank=True),
        ),
    ]
