# Generated by Django 2.0.7 on 2018-08-07 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_moviedbinfo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedbinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviedbinfo',
            name='last_synced',
            field=models.DateTimeField(blank=True),
        ),
    ]
