# Generated by Django 2.0.7 on 2018-08-09 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedbinfo',
            name='upcoming_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tagged_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
