# Generated by Django 2.0.7 on 2018-08-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_auto_20180809_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedbinfo',
            name='upcoming_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
